name: run ChronoScraper.py

on:
  schedule:
    - cron: "0 10 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo content
        uses: actions/checkout@v4

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.2"

      - name: set up environment
        run: |
          sudo snap install chromium
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: execute python script
        env:
          USER: ${{ secrets.USER }}
          PASSWORD: ${{ secrets.PASSWORD }}
          ACCOUNT: ${{ secrets.ACCOUNT }}
          WAREHOUSE: ${{ secrets.WAREHOUSE }}
          DATABASE: ${{ secrets.DATABASE }}
          SCHEMA: ${{ secrets.SCHEMA }}
          ROLE: ${{ secrets.ROLE }}
        run: |
          python ChronoScraper.py
